# Generated by Django 2.1.5 on 2019-04-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='detail',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='mileage',
            new_name='experience',
        ),
    ]
