# Generated by Django 2.1.5 on 2019-04-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20190405_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='ads',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='ads',
            new_name='owner',
        ),
    ]
