# Generated by Django 2.1.5 on 2019-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20190320_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=550),
        ),
    ]
