# Generated by Django 2.1.5 on 2019-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0004_auto_20190320_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='iso',
            name='iso',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
