# Generated by Django 2.1.5 on 2019-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0006_auto_20190320_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='justification',
            field=models.CharField(max_length=550),
        ),
    ]
