# Generated by Django 2.1.5 on 2019-03-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0007_auto_20190320_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
